require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.4'


target 'Alba' do
  config = use_native_modules!
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
  permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  #  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  #  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
   pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
   pod 'FBSDKCoreKit', :modular_headers => true
     pod 'FBSDKLoginKit', :modular_headers => true
     pod 'FBSDKShareKit', :modular_headers => true

   # Include all other configurations except `Debug-M1`
#   pod 'GoogleSignIn', :configurations => ['Debug', 'Staging', 'Release']

#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  #  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  #  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  #  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  #  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#   pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
#   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  #  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
#   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
#   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
#   pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly.podspec"
  #  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  #  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  #  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  #  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # target 'AlbaTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()
 
#    post_install do |installer|
#      installer.pods_project.targets.each do |target|
#         target.build_configurations.each do |config|
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#          end
#      end
#    end


#  post_install do |installer|
#    flipper_post_install(installer)
#  end
# end
#
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
end


# target 'Alba-tvOS' do
#   # Pods for Alba-tvOS

#   target 'Alba-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
  end
