import {createActions} from 'reduxsauce';

const {Types, Creators} = createActions({
  //selectedRegion: ['region'],
  onFail: null,
  homeScreen: null,
  homeScreenSuccess: ['data'],
  homeScreenType: ['Bool'],
  educationGrade: ['data'],
  educationGradeSuccess: ['data'],
  isTeacher: ['data'],
  isTeacherSuccess: ['data'],
  getStationeries: ['param'],
  getStationeriesSuccess: ['data'],
  setDateBirthday: ['data'],
  setGenderUser: ['Bool'],
  getLessonsTeachers: ['param'],
  getLessonsTeachersSuccess: ['data'],
  getCategories: null,
  getCategoriesSuccess: ['data'],
  getTeacherInfo: ['param'],
  getTeacherInfoSuccess: ['data'],
  setCategoryTitle: ['data'],
  setGradeTitle: ['data'],
  setCategoryTitleLesson: ['data'],
  setGradeTitleLesson: ['data'],
  setCategoryTitleCourses: ['data'],
  setGradeTitleCourses: ['data'],
  courseActivation: ['param'],
  courseActivationSuccess: ['data'],
  deleteFile: ['param'],
  deleteFileSuccess: ['data'],
  coursesScreen: ['param'],
  coursesScreenSuccess: ['data'],
  getEpisode: ['param'],
  setEpisodeData: ['data'],
  getNoteByUser: null,
  getNoteByUserSuccess: ['data'],
  setCurrentGradeId: ['data'],
  setCurrentCategoryId: ['data'],
  getAllUserCourseTitles: null,
  getAllUserCourseTitlesSuccess: ['data'],
  getAllUserExamsScore: null,
  getAllUserExamsScoreSuccess: ['data'],
  getUserSchedule: ['id'],
  getUserScheduleSuccess: ['data'],
  getAllUserExams: null,
  getAllUserExamsSuccess: ['data'],
  getUserExam: ['id'],
  getUserExamSuccess: ['data'],
  userAnswerToExam: ['param'],
  userAnswerToExamSuccess: ['data'],
  getContactInfo: null,
  getContactInfoSuccess: ['data'],
  getTeachersByLesson: ['id'],
  getTeachersByLessonSuccess: ['data'],
  convertYoutubeUrl: ['param'],
  convertYoutubeUrlSuccess: ['data'],
  userLogout: ['param'],
  userLogoutSuccess: ['data'],
  educationGradeStHome: ['data'],
  educationGradeStHomeSuccess: ['data'],
  getCategoriesStHome: null,
  getCategoriesStHomeSuccess: ['data'],
  getInforms: null,
  getInformsSuccess: ['data'],
  updateToken: ['param'],
  updateTokenSuccess: ['data'],
});

export const AppDataType = Types;
export default Creators;
